# Generated by Django 3.0.8 on 2020-07-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='birth_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
